spec:
  destination:
    server: [Your ARC Cluster]
  source:
    repoURL: [Your ArgoCD Repository URL]
    targetRevision: HEAD

runner:
  name: "arc-runner-set"
  namespace: "arc-runners"
  githubConfigUrl: ""
  createNamespace: "true"
  secretName: "runner-pat"
  createSecret: "true"  

