{{- if eq (toString .Values.runner.createNamespace) "true" }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.runner.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "0"
{{- end }}