{{- if eq (toString .Values.runner.createSecret) "true" }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: {{ .Values.runner.secretName }}
  namespace: {{ .Values.runner.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    github_token: Ag...GL
  template:
    metadata:
      creationTimestamp: null
      name: runner-pat
      namespace: arc-runners
    type: Opaque
{{- end }}
