apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: controller-manager
  namespace: actions-runner-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    github_token: Ag...1g
  template:
    metadata:
      creationTimestamp: null
      name: controller-manager
      namespace: actions-runner-system
    type: Opaque

